CREATE TABLE FUNCIONARIOS (
    IDFUNCIONARIO  NUMERIC(18,0) NOT NULL,
    CPF            VARCHAR(11) NOT NULL COLLATE PT_BR,
    NOME           VARCHAR(200) COLLATE PT_BR,
    EMAIL          VARCHAR(100) COLLATE PT_BR,
    TAMCAMISA      VARCHAR(10) NOT NULL COLLATE PT_BR,
    TAMCALCADO     NUMERIC(2,0) NOT NULL,
    OBSERVACAO     VARCHAR(300) COLLATE PT_BR
);

ALTER TABLE FUNCIONARIOS ADD PRIMARY KEY (IDFUNCIONARIO);

CREATE SEQUENCE GN_FUNCIONARIOS;